# Generated by Django 5.1.7 on 2025-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر ادمین است ؟'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='آیا کاربر فعاله ؟'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر مدیر است ؟'),
        ),
    ]
