# Generated by Django 5.1.7 on 2025-03-30 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='آدرس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post_Images/', verbose_name='تصویر پست')),
                ('description', models.TextField(verbose_name='محتوای مقاله')),
                ('like', models.PositiveIntegerField()),
                ('view', models.PositiveIntegerField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='متن کامنت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='blog.post', verbose_name='پست')),
            ],
        ),
    ]
