# Generated by Django 5.1.7 on 2025-04-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_like_remove_post_view_alter_like_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostViewsModel',
            new_name='PostViews',
        ),
    ]
