# Generated by Django 5.1.7 on 2025-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_postviewsmodel_postviews'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='like',
            name='session_key',
        ),
    ]
