# Generated by Django 5.1.7 on 2025-04-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_like_unique_together_remove_like_session_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostViews',
            new_name='PostVisit',
        ),
    ]
