# Generated by Django 5.1.7 on 2025-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_postviews_postvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
