# Generated by Django 5.1.7 on 2025-04-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_is_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replay',
            new_name='reply',
        ),
    ]
