# Generated by Django 5.1.7 on 2025-04-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_replay_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='replay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
    ]
