# Generated by Django 5.1.7 on 2025-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_reply_comment_replay_remove_comment_is_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replay',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
