# Generated by Django 5.1.7 on 2025-04-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
    ]
