# Generated by Django 5.1.7 on 2025-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replyed',
            field=models.BooleanField(default=False, verbose_name='پاسخ داده شده؟'),
        ),
    ]
