# Generated by Django 5.1.7 on 2025-07-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_replyed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='about-us/')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان سرویس')),
                ('icon', models.CharField(choices=[('globe', 'کره'), ('pencil', 'مداد'), ('laptop', 'لپ تاپ'), ('film', 'فیلم'), ('user', 'کاربر'), ('handshake-o', 'دست دادن'), ('book', 'کتاب'), ('line-chart', 'چارت'), ('graduation-cap', 'کلاه فارغ التحصیل'), ('gears', 'چرخ دنده'), ('mobile', 'موبایل'), ('support', 'ساپورت'), ('rocket', 'موشک')], default='globe', max_length=100, verbose_name='آیکن')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='StatsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان آمار')),
                ('icon', models.CharField(choices=[('globe', 'کره'), ('users', 'کاربران'), ('thumbs-up', 'لایک'), ('trophy', 'جام'), ('edit', 'ویرایش'), ('gift', 'جایزه'), ('graduation-cap', 'کلاه فارغ التحصیل'), ('code', 'کد'), ('bolt', 'صاعقه')], default='globe', max_length=100, verbose_name='آیکن')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('role', models.CharField(max_length=100, verbose_name='نقش')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_profile/', verbose_name='تصویر کاربر')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پروژه')),
                ('slug', models.CharField(max_length=100, verbose_name='اسلاگ')),
                ('employer', models.CharField(max_length=150, verbose_name='کارفرما')),
                ('history', models.DateField(verbose_name='تاریخ انجام')),
                ('address_project', models.CharField(max_length=200, verbose_name='آدرس پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
            },
        ),
    ]
