# Generated by Django 5.1.7 on 2025-07-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus_category_service_statssection_teammember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('github', 'github'), ('youtube', 'youtube'), ('telegram', 'telegram'), ('google-plus', 'google plus')], max_length=100, verbose_name='نوع شبکه اجتماعی')),
                ('link', models.URLField(blank=True, null=True, verbose_name='آدرس شبکه اجتماعی')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='home.aboutus')),
            ],
        ),
    ]
