# Generated by Django 5.1.7 on 2025-08-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about-us/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
