# Generated by Django 5.1.7 on 2025-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, help_text='پیشنهاد میشه سایز عکس 550 * 600 باشد', null=True, upload_to='about_us/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, choices=[('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('github', 'github'), ('youtube', 'youtube'), ('telegram', 'telegram'), ('google-plus', 'google plus')], max_length=100, null=True, verbose_name='نوع شبکه اجتماعی'),
        ),
    ]
