# Generated by Django 5.1.7 on 2025-08-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutus_image_alter_social_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teammember'),
        ),
        migrations.AlterField(
            model_name='social',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='home.aboutus'),
        ),
    ]
