# Generated by Django 5.1.7 on 2025-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact_reply_time_contact_send_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reply_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ارسال'),
        ),
    ]
