# Generated by Django 5.1.7 on 2025-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_contact_reply_time_alter_contact_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='آدرس'),
        ),
    ]
