# Generated by Django 5.1.7 on 2025-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='address_project',
            field=models.URLField(verbose_name='آدرس پروژه'),
        ),
    ]
